name: gemeini_chat
description: "Chat application with Google Gemini AI model."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_gemini: ^0.0.6
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  markdown_widget: ^2.3.2+2
  image_picker: ^1.0.5
  path: ^1.8.3
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

